// 导入app类型
import type { App } from 'vue';

import {
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElFooter,
  ElButton,
  ElSelect,
  ElCollapseTransition,
  ElSubMenu,
  ElMenu,
  ElMenuItemGroup,
  ElMenuItem,
  ElDropdown,
  ElDropdownMenu,
  ElRow,
  ElCol,
  ElProgress,
  ElDialog,
  ElCheckboxGroup,
  ElCheckbox,
  ElTabs,
  ElTabPane,
  ElDatePicker,
  ElForm,
  ElFormItem,
  ElInput,
  ElOption,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElDrawer,
  ElMessageBox,
  ElMessage,
  ElLoading,
  ElTag,
  ElTree,
  ElScrollbar,
  ElSwitch,
  ElRadio,
  ElIcon,
  ElPopover,
  ElDescriptions,
  ElDescriptionsItem,
  ElTooltip,
  ElUpload,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElConfigProvider
} from 'element-plus'

const components = [
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElFooter,
  ElButton,
  ElSelect,
  ElCollapseTransition,
  ElSubMenu,
  ElMenu,
  ElMenuItemGroup,
  ElMenuItem,
  ElDropdown,
  ElDropdownMenu,
  ElRow,
  ElCol,
  ElProgress,
  ElDialog,
  ElCheckboxGroup,
  ElCheckbox,
  ElTabs,
  ElTabPane,
  ElDatePicker,
  ElForm,
  ElFormItem,
  ElInput,
  ElOption,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElDrawer,
  ElMessageBox,
  ElMessage,
  ElLoading,
  ElTag,
  ElTree,
  ElScrollbar,
  ElSwitch,
  ElRadio,
  ElIcon,
  ElPopover,
  ElDescriptions,
  ElDescriptionsItem,
  ElTooltip,
  ElUpload,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElConfigProvider
]

const option = {
  size: 'small',
}

export default function introduceElement(app:App):void {
  components.forEach((component) => {
    app.use(component)
  })
  // eslint-disable-next-line no-param-reassign
  app.config.globalProperties.$ELEMENT = option
}
